"""测试里构造一份不受当前 shell 环境干扰的配置。"""

from __future__ import annotations

from app.config import Settings


def make_settings(
    *,
    app_env: str = "test",
    app_host: str = "127.0.0.1",
    app_port: int = 8000,
    enable_external_models: bool = False,
    llm_base_url: str = "",
    llm_api_key: str = "",
    llm_model: str = "",
    llm_temperature: float = 0.2,
    llm_timeout: float = 60,
    embedding_base_url: str = "",
    embedding_api_key: str = "",
    embedding_model: str = "",
    embedding_dimension: int | None = None,
    chroma_persist_dir: str = "./data/chroma",
    chroma_collection: str = "knowledge_base",
    chunk_size: int = 800,
    chunk_overlap: int = 120,
    default_top_k: int = 5,
    max_top_k: int = 20,
    max_question_chars: int = 2000,
    max_context_chars: int = 12000,
    retrieval_max_distance: float | None = None,
    hybrid_vector_top_k: int = 20,
    hybrid_bm25_top_k: int = 20,
    hybrid_final_top_k: int = 10,
    rrf_k: int = 60,
    reranker_enabled: bool = False,
    reranker_base_url: str = "",
    reranker_api_key: str = "",
    reranker_model: str = "",
    reranker_timeout: float = 60,
    reranker_candidate_top_k: int = 20,
    reranker_final_top_k: int = 5,
    llm_input_price_per_1m: float | None = None,
    llm_output_price_per_1m: float | None = None,
    embedding_price_per_1m: float | None = None,
    reranker_price_per_1k: float | None = None,
    max_upload_size_mb: int = 10,
    evaluation_dataset_path: str = "./data/evaluation/questions.json",
    evaluation_corpus_dir: str = "./data/evaluation/corpus",
    evaluation_reports_dir: str = "./data/evaluation/reports",
    judge_mode: str = "mock",
    judge_max_retries: int = 1,
    provider_max_retries: int = 2,
) -> Settings:
    return Settings(
        app_env=app_env,
        app_host=app_host,
        app_port=app_port,
        enable_external_models=enable_external_models,
        llm_base_url=llm_base_url,
        llm_api_key=llm_api_key,
        llm_model=llm_model,
        llm_temperature=llm_temperature,
        llm_timeout=llm_timeout,
        embedding_base_url=embedding_base_url,
        embedding_api_key=embedding_api_key,
        embedding_model=embedding_model,
        embedding_dimension=embedding_dimension,
        chroma_persist_dir=chroma_persist_dir,
        chroma_collection=chroma_collection,
        chunk_size=chunk_size,
        chunk_overlap=chunk_overlap,
        default_top_k=default_top_k,
        max_top_k=max_top_k,
        max_question_chars=max_question_chars,
        max_context_chars=max_context_chars,
        retrieval_max_distance=retrieval_max_distance,
        hybrid_vector_top_k=hybrid_vector_top_k,
        hybrid_bm25_top_k=hybrid_bm25_top_k,
        hybrid_final_top_k=hybrid_final_top_k,
        rrf_k=rrf_k,
        reranker_enabled=reranker_enabled,
        reranker_base_url=reranker_base_url,
        reranker_api_key=reranker_api_key,
        reranker_model=reranker_model,
        reranker_timeout=reranker_timeout,
        reranker_candidate_top_k=reranker_candidate_top_k,
        reranker_final_top_k=reranker_final_top_k,
        llm_input_price_per_1m=llm_input_price_per_1m,
        llm_output_price_per_1m=llm_output_price_per_1m,
        embedding_price_per_1m=embedding_price_per_1m,
        reranker_price_per_1k=reranker_price_per_1k,
        max_upload_size_mb=max_upload_size_mb,
        evaluation_dataset_path=evaluation_dataset_path,
        evaluation_corpus_dir=evaluation_corpus_dir,
        evaluation_reports_dir=evaluation_reports_dir,
        judge_mode=judge_mode,
        judge_max_retries=judge_max_retries,
        provider_max_retries=provider_max_retries,
    )
